---
abstract: 'convert between RDF and iCalendar'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - Directory
  - Event
  - RDF
  - SemWeb
  - 'Semantic Web'
  - Todo
  - hCal
  - hCalendar
  - iCal
  - iCalendar
  - vCalendar
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::iCalendar
name: RDF-iCalendar
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  DateTime: 0
  RDF::vCard: 0.010
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-iCalendar
  homepage: https://metacpan.org/release/RDF-iCalendar
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-icalendar
version: 0.003
